version: '3'

services:
  esme_organizer_db:
    image: postgres:15
    hostname: esme_organizer_db
    container_name: esme_organizer_db
    environment:
      POSTGRES_DB: esme
      POSTGRES_USER: ${ORGANIZER_DB_USER}
      POSTGRES_PASSWORD: ${ORGANIZER_DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "8001:5432"
