version: '3'

services:
  esme_organizer_ui:
    image: node:18
    hostname: esme_organizer_ui
    container_name: esme_organizer_ui
    working_dir: /usr/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        npm ci
        npm run build
        npm install -g serve
        serve -s build -l 3000
    volumes:
      - ../../../../js/frontends/organizer-ui:/usr/src/app:rw
      - ./config.json:/usr/src/app/src/config.json
    ports:
      - "80:3000"
