version: '3'

services:
  esme_cms_database:
    image: postgres:15
    hostname: esme_cms_database
    container_name: esme_cms_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: esme
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "54321:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  esme_cms_api:
    image: node:18
    hostname: esme_cms_api
    container_name: esme_cms_api
    working_dir: /usr/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        npm install
        npm run start:dev
    volumes:
      - ../../js/backends/cms:/usr/src/app:rw
    ports:
      - "8000:3000"
    depends_on:
      - esme_cms_database

  esme_messenger_api:
    image: golang:1.18
    hostname: esme_messenger_api
    container_name: esme_messenger_api
    working_dir: /usr/local/go/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        go install github.com/githubnemo/CompileDaemon@latest
        cd ./services/messenger
        CompileDaemon -log-prefix=false -build='go build' -command='./messenger'
    volumes:
      - ../../go:/usr/local/go/src/app:rw
    ports:
      - "8001:3000"
    depends_on:
      - esme_cms_database
      - esme_cms_api
