version: '3'

services:
  esme_organizer_db:
    image: postgres:15
    hostname: esme_organizer_db
    container_name: esme_organizer_db
    environment:
      POSTGRES_DB: esme
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "8001:5432"
    volumes:
      - ./organizer-db/data:/var/lib/postgresql/data

  esme_organizer_api:
    image: node:18
    hostname: esme_organizer_api
    container_name: esme_organizer_api
    working_dir: /usr/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        npm install
        npm run start:dev
    volumes:
      - ../../js/backends/organizer-api:/usr/src/app:rw
    ports:
      - "8000:8080"
    depends_on:
      - esme_organizer_db

  esme_participant_db:
    image: postgres:15
    hostname: esme_participant_db
    container_name: esme_participant_db
    environment:
      POSTGRES_DB: esme
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "8101:5432"
    volumes:
      - ./participant-db/data:/var/lib/postgresql/data

  esme_participant_api:
    image: golang:1.18
    hostname: esme_participant_api
    container_name: esme_participant_api
    working_dir: /usr/local/go/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        go install github.com/githubnemo/CompileDaemon@latest
        CompileDaemon -log-prefix=false -build='go build' -command='./participant-api'
    volumes:
      - ../../go/services/participant-api:/usr/local/go/src/app:rw
    ports:
      - "8100:8080"
    depends_on:
      - esme_participant_db
      - esme_chat_requests_queue

  esme_chat_requests_queue:
    image: rabbitmq:3-management
    hostname: esme_chat_requests_queue
    container_name: esme_chat_requests_queue
    environment:
      RABBITMQ_DEFAULT_USER: queue
      RABBITMQ_DEFAULT_PASS: queuePassword
    ports:
      - "8200:15672"
      - "56721:5672"

  esme_messenger_db:
    image: mongo:5-focal
    hostname: esme_messenger_db
    container_name: esme_messenger_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: dbPassword
    ports:
      - "8301:27017"
    volumes:
      - ./messenger-db/data:/data/db

  esme_messenger_db_admin:
    image: mongo-express:0.54
    hostname: esme_messenger_db_admin
    container_name: esme_messenger_db_admin
    ports:
      - "8302:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: developer
      ME_CONFIG_BASICAUTH_PASSWORD: dbPassword
      ME_CONFIG_MONGODB_ADMINUSERNAME: developer
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbPassword
      ME_CONFIG_MONGODB_SERVER: esme_messenger_db
      ME_CONFIG_MONGODB_PORT: 27017

  esme_messenger_api:
    image: golang:1.18
    hostname: esme_messenger_api
    container_name: esme_messenger_api
    working_dir: /usr/local/go/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        go install github.com/githubnemo/CompileDaemon@latest
        CompileDaemon -log-prefix=false -build='go build' -command='./messenger-api'
    volumes:
      - ../../go/services/messenger-api:/usr/local/go/src/app:rw
    ports:
      - "8300:8080"
    depends_on:
      - esme_organizer_db
      - esme_organizer_api
