version: '3'

services:
  esme_crm_db:
    image: postgres:15
    hostname: esme_crm_db
    container_name: esme_crm_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: esme
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "54321:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  esme_crm_api:
    image: node:18
    hostname: esme_crm_api
    container_name: esme_crm_api
    working_dir: /usr/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        npm install
        npm run start:dev
    volumes:
      - ../../js/backends/crm:/usr/src/app:rw
    ports:
      - "8000:3000"
    depends_on:
      - esme_crm_db

  esme_messenger_api:
    image: golang:1.18
    hostname: esme_messenger_api
    container_name: esme_messenger_api
    working_dir: /usr/local/go/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        go install github.com/githubnemo/CompileDaemon@latest
        CompileDaemon -log-prefix=false -build='go build' -command='./messenger'
    volumes:
      - ../../go/services/messenger:/usr/local/go/src/app:rw
    ports:
      - "8001:8080"
    depends_on:
      - esme_crm_db
      - esme_crm_api

  esme_dispatcher_rabbit:
    image: rabbitmq:3-management
    hostname: esme_dispatcher_rabbit
    container_name: esme_dispatcher_rabbit
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbitPassword
    ports:
      - "8002:15672"
      - "56721:5672"

  esme_dispatcher_api:
    image: golang:1.18
    hostname: esme_dispatcher_api
    container_name: esme_dispatcher_api
    working_dir: /usr/local/go/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        go install github.com/githubnemo/CompileDaemon@latest
        CompileDaemon -log-prefix=false -build='go build' -command='./dispatcher'
    volumes:
      - ../../go/services/dispatcher:/usr/local/go/src/app:rw
    ports:
      - "8003:8080"
    depends_on:
      - esme_dispatcher_rabbit

  esme_participant_db:
    image: postgres:15
    hostname: esme_participant_db
    container_name: esme_participant_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: esme
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "54322:5432"
    volumes:
      - ./participant-db/data:/var/lib/postgresql/data

  esme_participant_api:
    image: golang:1.18
    hostname: esme_participant_api
    container_name: esme_participant_api
    working_dir: /usr/local/go/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        go install github.com/githubnemo/CompileDaemon@latest
        CompileDaemon -log-prefix=false -build='go build' -command='./participant-api'
    volumes:
      - ../../go/services/participant-api:/usr/local/go/src/app:rw
    ports:
      - "8004:8080"
    depends_on:
      - esme_participant_db

