version: '3'

services:
  esme_crm_db:
    image: postgres:15
    hostname: esme_crm_db
    container_name: esme_crm_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: esme
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "54321:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  esme_crm_api:
    image: node:18
    hostname: esme_crm_api
    container_name: esme_crm_api
    working_dir: /usr/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        npm install
        npm run start:dev
    volumes:
      - ../../js/backends/crm:/usr/src/app:rw
    ports:
      - "8000:3000"
    depends_on:
      - esme_crm_db

  esme_messenger_api:
    image: golang:1.18
    hostname: esme_messenger_api
    container_name: esme_messenger_api
    working_dir: /usr/local/go/src/app
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        go install github.com/githubnemo/CompileDaemon@latest
        cd ./services/messenger
        CompileDaemon -log-prefix=false -build='go build' -command='./messenger'
    volumes:
      - ../../go:/usr/local/go/src/app:rw
    ports:
      - "8001:3000"
    depends_on:
      - esme_crm_db
      - esme_crm_api
